spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-detection-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      application-id: fraud-detection-app
      properties:
        bootstrap.servers: localhost:9092
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde


  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: 8edbe09af1e5f5
    password: 62bde491f1e7d5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
server:
  port: 9091
